# Generated by Django 3.2.4 on 2021-06-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
