# Generated by Django 3.2.4 on 2021-06-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_contacts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
