# Generated by Django 3.2.4 on 2021-06-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_alter_contacts_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
