# Generated by Django 3.2.4 on 2021-06-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_messages_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='status',
        ),
    ]
