# Generated by Django 3.2.4 on 2021-06-22 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0006_chat_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_group',
            name='members',
            field=models.ManyToManyField(default='', related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
