# Generated by Django 3.2.4 on 2021-06-22 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0007_alter_chat_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Chat.chat_group'),
        ),
    ]
