# Generated by Django 3.2.4 on 2021-06-22 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0009_remove_messages_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=1000000)),
                ('sent_date', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chat.chat_group')),
                ('receiver', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Group_Receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Group_Sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
