# Generated by Django 3.2.4 on 2021-06-22 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0010_group_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_messages',
            old_name='group',
            new_name='group_name',
        ),
    ]
