# Generated by Django 3.2.4 on 2021-06-22 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0011_rename_group_group_messages_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_messages',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Group_Receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group_messages',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Group_Sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
